### ISSUE TITLE
php artisan bar:import-recipes command is missing!

### ISSUE THREAD

**Issue by Borriborri** [zhdenny/bar_assistant_database#3]
Hi! 

When trying to use your database, it says that the bar: import-recipes is missing.
In the php artisan, it indeed shows that only these are existing: 
```
bar
  bar:anon                     [DEV] Anonymize data
  bar:delete-user              Delete user and all his data
  bar:export-recipes           Export data from a single bar. Available export types: datapack, schema, markdown, json-ld, xml, yaml
  bar:full-backup              Create a .zip file with the full backup of your Bar Assistant instance data
  bar:import-recipes           Import recipes exported as a Bar Assistant datapack
  bar:maintenance              This will remove unused images, update missing ABVs, fix ingredient sort and refresh cache
  bar:merge-ingredients        Merge multiple ingredients into one
  bar:refresh-search           Sync search engine indices with the latest Bar Assistant data
  bar:seed                     [DEV] Seed with random data
  bar:setup-meilisearch        Using master key is not recommended for API calls. This command will generate a new scoped API key and update the ENV file.
```

**Comment by zhdenny** [comment]
Recheck **all the instructions** I provided in the readme....this seems like you are missing something or made a typing or copy/paste mistake.

I just tested an import right now on my test bar assistant instance and it worked fine. I used the readme instructions to do it. Screenshot below showing everything.
![image](https://github.com/user-attachments/assets/3f9f81cd-a42c-4ba8-b7b3-2f62e7336e06)

**Comment by Borriborri** [comment]
Yes this is working now. 
Mistake was the following.

Used `curl` to download the dropbox. after that, you should change its name to a .zip name to be recognized.
